#pragma once
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <stack>
#include <string>
#include <vector>
#include <windows.h>

#include "Affair.h"
#include "Chest.h"
#include "ConstData.h"
#include "Dice.h"
#include "Enemy.h"
#include "Entity.h"
#include "Equipment.h"
#include "File.h"
#include "Field.h"
#include "Game.h"
#include "Interactive.h"
#include "Item.h"
#include "Process.h"
#include "Role.h"
#include "Skill.h"
#include "Store.h"
#include "UI.h"